[package]
name = "redirect-zone"
version = "0.1.0"
authors = ["Olly Legg <olly@51degrees.net>"]

[dependencies]
env_logger = "0.3.4"
hyper = "0.9.6"
regex = "0.1.73"
url = "1.1.1"

[dependencies.resolve]
git = "https://github.com/murarth/resolve"
